language: node_js
node_js:
    - node
    - 8
    - 6
before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- -- version 1.12.3
    - export PATH="$HOME/.yarn/bin:$PATH"
after_script: 'cat ./coverage/lcov.info | coveralls'
